name: Build WAR on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List build/libs directory contents for debugging
        run: ls -alh build/libs

      - name: Find and upload WAR file
        run: |
          WAR_FILE=$(ls build/libs/*.war | grep -v 'plain')
          echo "WAR_FILE=$WAR_FILE" >> $GITHUB_ENV

      - name: Upload WAR file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.WAR_FILE }}
          asset_name: JavaSysMonitor.war
          asset_content_type: application/zip